### ISSUE TITLE
Support KICAD 8.0

### ISSUE THREAD

**Issue by HaydenHu** [MitjaNemec/ReplicateLayout#70] opened 2024-03-05 03:47 UTC

**Comment by MitjaNemec** [comment] 2024-03-05 08:18
Already supported in https://github.com/MitjaNemec/ReplicateLayout/releases/tag/3.0.2

**Comment by HaydenHu** [comment] 2024-03-05 08:28
> Already supported in https://github.com/MitjaNemec/ReplicateLayout/releases/tag/3.0.2
![image](https://github.com/MitjaNemec/ReplicateLayout/assets/30103277/ddbe760c-1dab-434c-9584-3adcf9bea3a4)
The PCB is a project created by kicad7, which is saved as the kicad8 version, and an error message is reported when it is run

**Comment by HaydenHu** [comment] 2024-03-05 08:35
![image](https://github.com/MitjaNemec/ReplicateLayout/assets/30103277/2ff4ba1b-bd37-4800-ae29-96490fa6ef27)
I tested your PCB project file and it doesn't work as well
![image](https://github.com/MitjaNemec/ReplicateLayout/assets/30103277/c71075e1-e494-4795-bb2d-c78241cc5b96)
![image](https://github.com/MitjaNemec/ReplicateLayout/assets/30103277/ee712b83-2951-4258-b7fe-be5c9b895c4f)
![image](https://github.com/MitjaNemec/ReplicateLayout/assets/30103277/2b9ca3ae-5f7b-44cf-8419-743da72850e2)

**Comment by MitjaNemec** [comment] 2024-03-05 08:37
This can be something else. Did you just open the layout or the schematics also? Did you try opening the schematics and then updating layout from schematics? In any case, I'd appreciate if you attach the `replicate_layout.log` file. Are you in a position that you could share the project?

**Comment by HaydenHu** [comment] 2024-03-05 08:43
> 这可能是别的东西。您是否也打开了布局或原理图？您是否尝试过打开原理图，然后从原理图更新布局？无论如何，如果您附上文件，我将不胜感激。您是否能够共享该项目？`replicate_layout.log`

[yaokong.zip](https://github.com/MitjaNemec/ReplicateLayout/files/14492649/yaokong.zip)

**Comment by MitjaNemec** [comment] 2024-03-05 08:49
Thanks for sharing. It'll be a day or two before I can get the time to dive into the issue, so please be patient.

**Comment by MitjaNemec** [comment] 2024-03-05 19:55
OK, so I tried a couple of things and I am a bit stuck. With your project Kicad does not generate the metadata that the plugin requires even on my side. But if I start a fresh project with the same KiCad version, it generates the required metadata.

And without this metadata, the plugin can not run so the crash is expected (though it could be handled a bit gracefully)

So at the moment I am quite stumped why with this project the required metadata is not generated. And I assume the same issue is present in the project where you shared screenshots.

So can you answer me the folowing points:

1. Can I share your project further so that I can ask the KiCad team if this is maybe a bug within KiCad itself? As I suspect that there maybe a bug within KiCad.

2. And as an additional info. Can you check your projects it the layout file has `sheetfile` and `sheetname`definitions with the footprint? E.g. Your project has the following content between 176 and 179 (part of R5 footprint definition)
```
		(property ki_fp_filters "R_*")
		(path "/6d8410d0-3522-433e-8806-3a03cee17d79/5d1fc139-657d-4b0c-b115-8cdc341268bd")
		(attr smd)
		(fp_line
```
while my project contain two additional fields with every footprint
```
		(property ki_fp_filters "C_*")
		(path "/f0e5fb45-7773-42fb-994d-a9942058f64b/020acf9b-7f91-417f-9b29-9ef955cdb1af")
		(sheetname "Untitled Sheet")
		(sheetfile "untitled.kicad_sch")
		(attr smd)
		(fp_line
```

3. I have a hunch that the bug maybe related to the locale (language) setting. Can you switch KiCad language to English. then restart KiCad and create a new project containing one symbol with defined footprint on the root schematics and one symbol with footprint defined in a hierarchical page. Hierarchical page should have a name and filename from pure ASCII characters (English alphabet)

**Comment by HaydenHu** [comment] 2024-03-06 02:49
Using kicad8.0, I created layered schematics and PCBs under the software language settings of Chinese and English respectively, and after testing, the results are similar to the results obtained from the test engineering files you provided，It's all footprints that will run around and it cannot get the correct result

**Comment by MitjaNemec** [comment] 2024-03-06 13:18
Sorry but we seem to have language issue, so I'd like you to confirm/deny the following:
1. You've created two project as requested with different language settings?
2. Both projects behave the same?
3. With both projects you can see the `sheetfile` and `sheetname` properties within the layout file?

If answer to all of the above questions is "yes" then there is something wrong with you project. possibly there is a bug in KiCad. If the answer to 3 is "no" then there is an issue with your KiCad setup or a bug in KiCad.

Additionally, can I share the project you've attached?

**Comment by HaydenHu** [comment] 2024-03-07 03:41
1.yes
2.yes
3.yes

**Comment by HaydenHu** [comment] 2024-03-07 03:58
yaokong.zip
This is a file created by kicad6.0, and an error is reported. The new files created in kicad8 will work with your plug-in

**Comment by solverstin** [comment] 2024-03-25 09:59
Forgive me if my comment is out of topic, but I've tried to install this plugin on KiCAD 8.99 (build locally from gitlab repository)... and it failed to install (from file) with "version incompatible with KiCAD" error. 

Did anybody have that same experience? Is there anything I could do to help bring up this plugin to v8.99 compatibility?

**Comment by MitjaNemec** [comment] 2024-03-25 10:12
The plugin might or might not work with 8.99. 
>  Is there anything I could do to help bring up this plugin to v8.99 compatibility?
you might not need to do anything.

As I don't support the compatibility with 8.99 the plugin is marked so that PCM will not install it. So your only issue is how to install the plugin, so that you can check if it works. The easiest way would be to copy the plugin contents into the folder where KiCad can find it (on MSW that would be in subfolder within "%APPDATA%\kicad\8.99\scripting\plugins")

**Comment by MitjaNemec** [comment] 2024-03-25 10:14
Due to following reasons:
- this is likely a KiCad bug
- this is really an unlikely edge case
- lack of info to reproduce this issue
I am closing this issue

**Closed as completed by MitjaNemec** 2024-03-25 10:14 UTC
